language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: DuN1pJIRYu9IwNidMzJVCZFHMZJNmkbB3M5o0Rf/b8eHq5fE4pUuBFoAFhzOb65qk0OO1PaV1FM7tbKOETuNv382pERk2SPdgBDlKpU2gNtLAQPlFiPur+OxnHinQNAX6QI/3WUFmKPPo3KR2BI2Xzh8eoVU/Gptv2IrBVEjCelVfRIAzRklJddj+B/GznRjieRGJ+cHwp4CJqLCepyq50OHXwvGT3gR363CaMi8p0R2iWZKlUdDltnL8FomMi/Oq3zW5krhIWjMm9LJ/h13cnRT6Qv64OKC0FxxVp0koYlYMAUEphCzzQ5kv6DHbZgyHLg0gkYihSoFEHYBm5099fc95LFKrsCgOsv+IXly56RHMG+0eRd/CNIC8/A/se6cDulGXBwhdD2EAaOq8EtZ0X6CWgqOHF6AAuECUKjqdsyKffUyqPHwkMBB4k30Q3p8yBeXgM3qmcXOf+Zeh0ejv48mqjOUFSsVt4Z66+iJ9wmYWonvd8U2DRIOqi5eUHAfXQ8BmdDYGJ9Aw71tYlpHaqK1Cjug01T04ofiSi5RuCMwmrMf024zfXBJxMvDtgbStk4SaiWenS1D0YLtCYoDMlJpWP7bRgkLCnp7vWGZPQVA6Q0dO1ayXpa88EeM2UxfoWmQhxP3DHt88l/EWIVX/xpo7uxZ89FjzmpBUR5QVNE=
  on:
    tags: true