language: node_js
node_js:
- '8.2'
deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: kqJB9h66URGjZG+ythZ0WyJDOtJvUhnFKzEAU9nG0wPgaKyaIiCoQyM3r+zCYp+9oKGkoTjpf5Q8a/6ybc5ACRQU8kqlfNHlVr4/RbW+X1vIMUZLVIHQRkGxvu4rSnGew81yFc4VAdsWivlCULd8L+r347hAcL4/wmGnMDmqjlJajLD1VUHUJ57qr4YCzVhq6QVMcrU3XrA+vfKYYGN6jRdtW7+83gi1boZKzoRChwSvGJ3jObsPnjgsq8omyFmwe71vYYL6/CwfzkdNQNOtrxAfxM3q/R5Ix3hvLfnfYsZCV2HNQNbtITEv8M374LrT2oFZSC3XM8y0Q+QBAPgjImiqXOwDQdicFim93iguBXa+EYXuyp60g+7j8XxdsB11dM6jGdzELFpo1EJOH4utRDweuWHWfeNilYZGsk7raPVIMf5apJEB1SGMMp3srgmNdM7wkrYKGhbOrqxpspVpJorxO1moThf/0eMl4EPgMnHOh5sHDtjC4Cwyg2HTOSYQeYZx5C+MkhjeATz4jjDfJJDfh4TuKqo6Vg3mQi4J7N3VDx5Vf6thFcJ3VEMgsU1RBgBhpVH4YNoaGzJlDkDoyj9xkuVfcM1P/blwwifOOMWkGh7Kz0XbNXTplWyeV5gEuoYxhzYY1d+O7nkHbe4LJeEa4ruiXlPMqEhGqdLLtac=
  on:
    tags: true
    repo: LuvDaSun/synchronize-async
